export const SET_FAVORITES = "favorites/SET_FAVORITES";
export const ACCEPT_ADD_TO_FAVORITES = "favorites/ACCEPT_TO_FAVORITES";
export const ACCEPT_REMOVE_FROM_FAVORITES =
	"favorites/ACCEPT_REMOVE_FROM_FAVORITES";
