export const SET_CATEGORIES = "filters/SET_CATEGORIES";
export const ACCEPT_ACTIVE_CATEGORY = "filters/ACCEPT_ACTIVE_CATEGORY";
export const SET_SORT_BY = "filters/SET_SORT_BY";
export const SET_FILTERBAR_FILTERS = "filters/SET_FILTERBAR_FILTERS";
export const SET_IS_LOADING_FILTERBAR_FILTERS =
	"filters/SET_IS_LOADING_FILTERBAR_FILTERS";
export const SET_ACTIVE_FILTERBAR_FILTERS =
	"filters/SET_ACTIVE_FILTERBAR_FILTERS";
export const RESET_ACTIVE_FILTERS = "filters/RESET_ACTIVE_FILTERS";
export const SET_ACTIVE_SEARCH = "filters/SET_ACTIVE_SEARCH";
