export const SET_IS_ACTIVE_CALLBACK_POPUP =
	"popups/SET_IS_ACTIVE_CALLBACK_POPUP";

export const SET_TEXT_POPUP = "popups/SET_TEXT_POPUP";

export const SET_IS_ACTIVE_ORDER_SUCCESS_POPUP =
	"popups/SET_IS_ACTIVE_ORDER_SUCCESS_POPUP";
